### ISSUE TITLE
Funnel Not Emptying Bucket

### ISSUE THREAD

**Issue by ChloeDawn** [shadowfacts/Funnels#5]
**Mod version:** [1.2.0](https://minecraft.curseforge.com/projects/funnels/files/2350049)
**Forge version:** [1.11-13.19.1.2188](http://files.minecraftforge.net/maven/net/minecraftforge/forge/1.11-13.19.1.2188/forge-1.11-13.19.1.2188-changelog.txt)

**Funnel does not consume the fluid when right-clicking on it with a bucket.**
Fluids placed by the funnel are also not getting a block update, I don't know if that's intentional or not.

**Example with water:**

![water_before](https://cloud.githubusercontent.com/assets/9869940/21058021/f6129fdc-be33-11e6-8b5d-8bdfb02825ca.png)
![water_after](https://cloud.githubusercontent.com/assets/9869940/21058022/f634323c-be33-11e6-9704-b613caa50e2d.png)
![water_placed](https://cloud.githubusercontent.com/assets/9869940/21058023/f640e9be-be33-11e6-921c-e0001259ce44.png)

**Example with lava:**

![lava_before](https://cloud.githubusercontent.com/assets/9869940/21058082/47ccaaac-be34-11e6-9a32-f771e3f80dba.png)
![lava_after](https://cloud.githubusercontent.com/assets/9869940/21058083/47dd8e30-be34-11e6-8357-8f84f2939efb.png)
![lava_placed](https://cloud.githubusercontent.com/assets/9869940/21058084/47ec0dca-be34-11e6-95fb-a760492bb520.png)

**Comment by ChloeDawn** [comment]
Note also that when there is fluid in the funnel, and it is above an existing fluid block in the world, the funnel is emptying itself regardless, and essentially voiding it's contents.

**Comment by shadowfacts** [comment]
Does this occur with the Forge bucket and the Vanilla bucket or just one or the other?

**Comment by ChloeDawn** [comment]
I was originally testing with `B:replaceVanillaBucketModel` set to `false`.

I set it to `true` and can confirm that fluid is also not consumed with the Forge bucket.
Tested with [Actually Additions'](https://minecraft.curseforge.com/projects/actually-additions) Oil Bucket.

![2016-12-09_21 53 54](https://cloud.githubusercontent.com/assets/9869940/21065793/0e9edcac-be5a-11e6-9ef2-687304ce3ee2.png)

**Comment by shadowfacts** [comment]
Fixed in 1.2.1 for MC 1.11 and 1.1.2 for MC 1.10.2, both of which will be released shortly.
